# Generated by Django 2.1.3 on 2018-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20181129_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
