# Generated by Django 2.1.3 on 2018-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_project1'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='role',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
